version: '3'
services:

    backend:
        build: 
            context: ./
            dockerfile: .dockerfiles/backend_dev.Dockerfile
        restart: always
        depends_on:
            - postgres
            #postgres:
            #    condition: service_healthy
        networks:
            - custom-bridge
        ports:
            - "9000:9000"

    #backend_test:
    #    build: 
    #        context: ./
    #        dockerfile: .dockerfiles/backend_dev.Dockerfile
    #    restart: always
    #    depends_on:
    #        postgres:
    #            condition: service_healthy
    #    command: yarn run test:watch
    #    networks:
    #        - custom-bridge
    #    ports:
    #        - "9005:9005"
    #    volumes: 
    #        - ./backend:/opt/app
        
    postgres:
        build:
            context: ./
            dockerfile: .dockerfiles/db.Dockerfile
        restart: always
        environment:
            POSTGRES_DB: nba_db
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'passu123'
        #healthcheck:
        #    test: ["CMD-SHELL", "pg_isready -U postgres"]
        #    interval: 20s
        #    timeout: 10s
        #    retries: 5
        networks:
            - custom-bridge
        ports:
            - '5432:5432'

    adminer:
        image: adminer:4.7.7
        restart: always
        ports:
            - '80:8080'
        depends_on:
            - postgres
            #postgres:
            #    condition: service_healthy
        networks:
            - custom-bridge

networks:
    custom-bridge: