version: '3.8'
services:

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'passu123'
        networks:
            - custom-bridge
        ports:
            - '5432:5432'
        volumes:
            - tietokanta_kurssi-db-data:/var/lib/postgresql/data

    pgAdmin:
        container_name: pgAdmin
        image: dpage/pgadmin4:latest
        restart: always
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin'
            PGADMIN_DEFAULT_PASSWORD: 'passu123'
            PGADMIN_LISTEN_PORT: '80'
        networks:
            - custom-bridge
        ports:
            - '80:80'
        volumes:
            - tietokanta_kurssi-pgadmin-data:/var/lib/pgadmin

networks:
    custom-bridge: